on:
- push
- pull_request

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: install golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: checkout code
      uses: actions/checkout@v2

    - name: run tests
      run: make test